# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# This file contains a template configuration file, which is typically
# placed as .hlint.yaml in the root of your project


# Specify additional command line arguments
#
# - arguments: [--color, --cpp-simple, -XQuasiQuotes]


# Control which extensions/flags/modules/functions can be used
#
# - extensions:
#   - default: false # all extension are banned by default
#   - name: [PatternGuards, ViewPatterns] # only these listed extensions can be used
#   - {name: CPP, within: CrossPlatform} # CPP can only be used in a given module
#
# - flags:
#   - {name: -w, within: []} # -w is allowed nowhere
#
# - modules:
#   - {name: [Data.Set, Data.HashSet], as: Set} # if you import Data.Set qualified, it must be as 'Set'
#   - {name: Control.Arrow, within: []} # Certain modules are banned entirely
#
# - functions:
#   - {name: unsafePerformIO, within: []} # unsafePerformIO can only appear in no modules


# Add custom hints for this project
#
# Will suggest replacing "wibbleMany [myvar]" with "wibbleOne myvar"
# - error: {lhs: "wibbleMany [x]", rhs: wibbleOne x}


# Turn on hints that are off by default
#
# Ban "module X(module X) where", to require a real export list
# - warn: {name: Use explicit module export list}
#
# Replace a $ b $ c with a . b $ c
# - group: {name: dollar, enabled: true}
#
# Generalise map to fmap, ++ to <>
# - group: {name: generalise, enabled: true}


# Ignore some builtin hints
# - ignore: {name: Use let}
# - ignore: {name: Use const, within: SpecialModule} # Only within certain modules


# Define some custom infix operators
# - fixity: infixr 3 ~^#^~


# To generate a suitable file for HLint do:
# $ hlint --default > .hlint.yaml

# hints found in src/IOTS.hs
- warn: {lhs: "\"import * as t from 'io-ts'\"", rhs: "preamble"}

# hints found in src/IOTS/Leijen.hs
- warn: {lhs: "displayTStrict (renderPretty 0.8 200 a)", rhs: "render a"}
- warn: {lhs: "textStrict (Text.pack a)", rhs: "stringDoc a"}
- warn: {lhs: "inset ((vsep . punctuate comma) a)", rhs: "indentedList a"}
- warn: {lhs: "linebreak <> indent 4 a <> linebreak", rhs: "inset a"}
- warn: {lhs: "brackets (indentedList a)", rhs: "jsArray a"}
- warn: {lhs: "braces (indentedList a)", rhs: "jsObject a"}
- warn: {lhs: "parens (indentedList a)", rhs: "jsParams a"}
